site_name: OpenFF Standards
theme:
  name: material
nav:
  - Home: 'index.md'
  - Standards:
    - 'SMIRNOFF': 'standards/smirnoff.md'
    - 'QC Data Submission': 'standards/qc-data-submission.md'
  - Enhancement Proposals:
    - 'OFF-EP 0 - Purpose and Process': 'enhancement-proposals/off-ep-0000.md'
    - 'OFF-EP X - Template': 'enhancement-proposals/off-ep-template.md'
    - 'OFF-EP 1 - Clarify that constraint distances override equilibrium bond distances': 'enhancement-proposals/off-ep-0001.md'
    - 'OFF-EP 5 - Resolve ambiguity over PME electrostatics for nonperiodic systems': 'enhancement-proposals/off-ep-0005.md'
    - 'OFF-EP 6 - Define virtual site exclusion policy': 'enhancement-proposals/off-ep-0006.md'

markdown_extensions:
  - admonition
